name: Verify Supreme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Drake foundry
        uses: actions/checkout@v4
        with:
          repository: SlimefunNewHorizons/drakes-slimefun-labs
          path: drakes-slimefun-labs
          ref: main
      - name: Checkout Slimefun Drake
        uses: actions/checkout@v4
        with:
          repository: SlimefunNewHorizons/Slimefun4-Drake
          path: slimefun-core
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install Drake build dependencies
        working-directory: drakes-slimefun-labs
        run: |
          mvn -B -ntp -N -DskipTests install
          mvn -B -ntp -DskipTests -f sources/internal-metadata/patches/commons-lang-drake-patched/pom.xml install
          mvn -B -ntp -DskipTests -f sources/dough-core/pom.xml install
          mvn -B -ntp -DskipTests -Dslimefun.drake.version=11.0-Drake-1.21.11-SNAPSHOT -f ../slimefun-core/pom.xml install
          mvn -B -ntp -Dmaven.test.skip=true -f sources/batch-2-expansion/SefiLib/pom.xml install
          mvn -B -ntp -Dmaven.test.skip=true -f sources/batch-2-expansion/InfinityLib/pom.xml install
          mvn -B -ntp -Dmaven.test.skip=true -f sources/drakes-labs-autoupdate/pom.xml install

      - name: Verify with Maven
        run: mvn -B -ntp clean verify
